// Offline HLSL-to-header compiler.  It is intentionally independent of game.exe.
#include <windows.h>
#include <d3dcompiler.h>
#include <cstdio>
#include <fstream>
#include <cstring>
#include <new>
#include <string>
#include <vector>

class LocalInclude final : public ID3DInclude {
public:
  explicit LocalInclude(const char *sourcePath) : root_(sourcePath ? sourcePath : "") {
    const std::string::size_type slash = root_.find_last_of("\\/");
    root_ = slash == std::string::npos ? "." : root_.substr(0, slash);
  }

  HRESULT STDMETHODCALLTYPE Open(D3D_INCLUDE_TYPE, LPCSTR name, LPCVOID,
                                 LPCVOID *data, UINT *bytes) override {
    if (!name || !data || !bytes) return E_INVALIDARG;
    std::ifstream input(root_ + "\\" + name, std::ios::binary);
    if (!input) input.open(root_ + "/" + name, std::ios::binary);
    if (!input) return E_FAIL;
    std::vector<char> content((std::istreambuf_iterator<char>(input)),
                              std::istreambuf_iterator<char>());
    if (content.empty()) return E_FAIL;
    char *copy = new (std::nothrow) char[content.size()];
    if (!copy) return E_OUTOFMEMORY;
    std::memcpy(copy, content.data(), content.size());
    *data = copy;
    *bytes = static_cast<UINT>(content.size());
    return S_OK;
  }

  HRESULT STDMETHODCALLTYPE Close(LPCVOID data) override {
    delete[] static_cast<const char *>(data);
    return S_OK;
  }

private:
  std::string root_;
};

static bool emit(ID3DBlob *blob, const char *name, std::ofstream &out) {
  const unsigned char *bytes = static_cast<const unsigned char *>(blob->GetBufferPointer());
  const size_t count = blob->GetBufferSize();
  out << "alignas(4) inline constexpr unsigned char " << name << "[] = {\n  ";
  for (size_t i = 0; i < count; ++i) {
    char item[8];
    std::snprintf(item, sizeof(item), "0x%02X", unsigned(bytes[i]));
    out << item << (i + 1 == count ? "" : ",");
    if ((i + 1) % 12 == 0 && i + 1 != count) out << "\n  ";
    else out << " ";
  }
  out << "\n};\ninline constexpr unsigned " << name << "Size = " << count << ";\n\n";
  return bool(out);
}

int main(int argc, char **argv) {
  if (argc != 3) {
    std::fprintf(stderr, "usage: edge_aa_compile input.hlsl output.hpp\n");
    return 2;
  }
  std::ifstream input(argv[1], std::ios::binary);
  const std::string source((std::istreambuf_iterator<char>(input)),
                           std::istreambuf_iterator<char>());
  if (!input.good() && !input.eof()) return 2;
  HMODULE compiler = LoadLibraryA("d3dcompiler_43.dll");
  using Compile = HRESULT (WINAPI *)(const void *, SIZE_T, const char *,
      const D3D_SHADER_MACRO *, ID3DInclude *, const char *, const char *, UINT,
      UINT, ID3DBlob **, ID3DBlob **);
  FARPROC rawCompile = compiler ? GetProcAddress(compiler, "D3DCompile") : nullptr;
  Compile compile = nullptr;
  static_assert(sizeof(compile) == sizeof(rawCompile), "function pointer size");
  std::memcpy(&compile, &rawCompile, sizeof(compile));
  if (!compile) { if (compiler) FreeLibrary(compiler); return 2; }
  const char *entries[] = {"EdgeAALow", "EdgeAAHigh"};
  const char *names[] = {"low", "high"};
  const char *presets[] = {"12", "39"};
  ID3DBlob *blobs[2] = {};
  LocalInclude includes(argv[1]);
  for (unsigned i = 0; i != 2; ++i) {
    const D3D_SHADER_MACRO macros[] = {
        {"FXAA_PC", "1"}, {"FXAA_HLSL_3", "1"},
        {"FXAA_QUALITY__PRESET", presets[i]},
        {"FXAA_GREEN_AS_LUMA", "0"}, {"FXAA_LUMA_SEPARATE_R8", "0"},
        {"FXAA_GATHER4_ALPHA", "0"}, {"FXAA_DISCARD", "0"},
        {"FXAA_BOUNDED_RGB_LUMA", "1"}, {nullptr, nullptr}};
    ID3DBlob *errors = nullptr;
    HRESULT hr = compile(source.data(), source.size(), argv[1], macros, &includes,
                         entries[i], "ps_3_0", D3DCOMPILE_ENABLE_STRICTNESS,
                         0, &blobs[i], &errors);
    if (FAILED(hr)) {
      if (errors) std::fwrite(errors->GetBufferPointer(), 1, errors->GetBufferSize(), stderr);
      if (errors) errors->Release();
      for (ID3DBlob *blob : blobs) if (blob) blob->Release();
      FreeLibrary(compiler);
      return 1;
    }
    if (errors) errors->Release();
  }
  const std::string temporary = std::string(argv[2]) + ".tmp-" +
                                std::to_string(GetCurrentProcessId());
  std::ofstream output(temporary, std::ios::binary | std::ios::trunc);
  if (!output) {
    for (ID3DBlob *blob : blobs) blob->Release();
    FreeLibrary(compiler);
    return 2;
  }
  output << "// Generated by tools/edge_aa_compile.cpp; do not edit.\n"
            "#pragma once\nnamespace gurumin { namespace edge_aa_bytecode {\n\n";
  for (unsigned i = 0; i != 2; ++i) {
    if (!emit(blobs[i], names[i], output)) {
      output.close();
      DeleteFileA(temporary.c_str());
      for (ID3DBlob *blob : blobs) if (blob) blob->Release();
      FreeLibrary(compiler);
      return 1;
    }
    blobs[i]->Release();
    blobs[i] = nullptr;
  }
  output << "} } // namespace gurumin::edge_aa_bytecode\n";
  output.close();
  const int result = output && MoveFileExA(temporary.c_str(), argv[2],
                                             MOVEFILE_REPLACE_EXISTING) ? 0 : 1;
  if (result) DeleteFileA(temporary.c_str());
  FreeLibrary(compiler);
  return result;
}
